// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJujAJW2biPoc67tTw5nttffM_sCIUPdA',
    appId: '1:261042307752:web:1ec1dace1e2ca3a743b89d',
    messagingSenderId: '261042307752',
    projectId: 'srmproj',
    authDomain: 'srmproj.firebaseapp.com',
    storageBucket: 'srmproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5tbqzbqVlx3W_iGZWvrI049CIhzwkro',
    appId: '1:261042307752:android:0fee959fa3d9339843b89d',
    messagingSenderId: '261042307752',
    projectId: 'srmproj',
    storageBucket: 'srmproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDffEPg0Aeu5BIwzWqwUlCNv5YJgerORjI',
    appId: '1:261042307752:ios:63b7b3a8aa6e277b43b89d',
    messagingSenderId: '261042307752',
    projectId: 'srmproj',
    storageBucket: 'srmproj.appspot.com',
    iosBundleId: 'com.example.fuel',
  );
}
